set nocompatible
set autoindent
set cindent
set smartindent
set wrap
set nowrapscan
set nobackup
set noswapfile
set ruler
set shiftwidth=4
set number
set encoding=utf-8
set fileencodings=utf-8,euckr
set tenc=utf-8
set expandtab
set hlsearch
set ignorecase
set tabstop=4
set lbr
set incsearch
set cursorline
set laststatus=2
syntax on
filetype plugin indent on
set background=dark
set backspace=eol,start,indent
set history=1000
highlight Comment term=bold cterm=bold ctermfg=4
set t_Co=256

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'nanotech/jellybeans.vim'
Plugin 'scrooloose/syntastic'
Plugin 'airblade/vim-gitgutter'
Plugin 'scrooloose/nerdtree'
Plugin 'AutoComplPop'
Plugin 'prabirshrestha/vim-lsp'
Plugin 'majutsushi/tagbar'
Plugin 'blueyed/vim-diminactive'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'nathanaelkane/vim-indent-guides'
call vundle#end()

colorscheme jellybeans
let NERDTreeWinPos = "left"
nmap <F7> :NERDTree<CR>
nmap <F8> :TlistToggle<CR>
let Tlist_Ctags_Cmd = "/usr/bin/ctags"
let Tlist_Inc_Winwidth = 0
let Tlist_Exit_OnlyWindow = 0
let Tlist_Auto_Open = 0"

"ctags
set tags=./tags,tags
set tagbsearch

"cscope
set csprg=/usr/bin/cscope

set csto=0
set cst
set nocsverb

if filereadable("./cscope.out")
        cs add cscope.out
else
        cs add /usr/src/linux/cscope.out
endif
set csverb

let Tlist_Auto_Open =1
